import test from 'node:test';
import assert from 'node:assert/strict';
import {handleSeeding,validateCreate,applyOperations,validatePayload} from '../scripts/seeding-store.mjs';
import {callSeedingTool,createSeedingRestClient,seedingRpc} from '../scripts/seeding-mcp.mjs';
const input={name:'NEW PROJECT',brand:'BRAND',productName:'PANTS',publicFormUrl:'https://docs.google.com/forms/d/e/example/viewform',editFormUrl:'https://docs.google.com/forms/d/example/edit',responseSheetUrl:'https://docs.google.com/spreadsheets/d/abcdefghijklmnop/edit',responseSheetName:'Form Responses 1',responseSheetGid:1590883012,startDate:'2026-10-10',targetCount:10};
const initial=()=>({schemaVersion:1,unknown:{preserve:true},projects:[{id:'old',name:'EXISTING',version:10}],creators:[],seedings:[]});
function remote(mode){let doc=initial(),rev=1,uploads=0;return {env:{DROPBOX_APP_KEY:'a',DROPBOX_APP_SECRET:'b',DROPBOX_REFRESH_TOKEN:'c'},get:()=>structuredClone(doc),uploads:()=>uploads,fetchImpl:async(url,init)=>{
 if(url.includes('oauth2/token'))return new Response(JSON.stringify({access_token:'isolated'}));
 if(url.endsWith('/download'))return mode==='missing'?new Response('{}',{status:409}):new Response(JSON.stringify(doc),{headers:{'dropbox-api-result':JSON.stringify({rev:'rev'+rev})}});
 if(url.endsWith('/upload')){uploads++;const arg=JSON.parse(init.headers['Dropbox-API-Arg']);assert.deepEqual(arg.mode,{'.tag':'update',update:'rev'+rev});assert.equal(arg.autorename,false);
 if(mode==='ambiguous')throw Error('network');
 if(mode==='race'||mode==='duplicate-race'){if(mode==='duplicate-race')doc.projects.push({...input,id:'raced',version:1});return new Response('{}',{status:409});}
 if(arg.mode.update!=='rev'+rev)return new Response('{}',{status:409});doc=JSON.parse(init.body);rev++;return new Response('{}');}throw Error('unexpected URL');}};}
const path='/api/ai-audit/seeding/projects';
test('create → GET → update, version1, correct Sheet IDs and existing data frozen',async()=>{const r=remote(),before=r.get();const c=await handleSeeding('POST',path,null,input,r);assert.equal(c.status,201);assert.equal(c.etag,'"seeding-1"');assert.equal(c.body.project.targetCount,10);assert.equal(c.body.project.responseSheetId,'abcdefghijklmnop');assert.equal(c.body.project.responseSheetGid,1590883012);assert.deepEqual(r.get().projects[0],before.projects[0]);assert.deepEqual(r.get().unknown,before.unknown);assert.deepEqual(r.get().seedings,[]);const g=await handleSeeding('GET','/api/ai-audit/seeding/project',input.name,null,r);assert.deepEqual(g.body.project,c.body.project);const u=await handleSeeding('PUT','/api/ai-audit/seeding/project',input.name,{version:1,operations:[{type:'update_project',patch:{targetCount:12}}]},r);assert.equal(u.body.project.version,2);assert.equal(u.body.project.targetCount,12);await assert.rejects(()=>handleSeeding('POST',path,null,{...input,name:' new project '},r),e=>e.status===409&&e.message==='duplicate_project_name');assert.equal(r.uploads(),2);});
test('invalid input rejected before storage',async()=>{for(const patch of [{targetCount:0},{targetCount:'10'},{startDate:'2026-02-30'},{endDate:'2026-10-01'},{responseSheetGid:-1},{responseSheetUrl:'https://evil.test/spreadsheets/d/abcdefghijklmnop/edit'},{publicFormUrl:'javascript:alert(1)'},{name:' '},{seedings:[]}]){const r=remote();await assert.rejects(()=>handleSeeding('POST',path,null,{...input,...patch},r),e=>e.status===400);assert.equal(r.uploads(),0);}});
test('concurrent creation CAS conflict, duplicate race, ambiguous network and missing store never retry',async()=>{for(const mode of ['race','duplicate-race','ambiguous','missing']){const r=remote(mode);if(mode==='race'||mode==='duplicate-race'){const result=await handleSeeding('POST',path,null,input,r);assert.equal(result.status,409);assert.equal(result.body.error,mode==='race'?'version_conflict':'duplicate_project_name');}else await assert.rejects(()=>handleSeeding('POST',path,null,input,r),e=>e.status===(mode==='missing'?503:502));assert.equal(r.uploads(),mode==='missing'?0:1);}});
test('direct pickup has no parcel status/tracking and retains pickup-based upload deadline',()=>{const d=initial(),ops=[{type:'add_seeding',instagramId:'recipient',patch:{fulfillmentMethod:'pickup',pickedUpAt:'2026-10-10'}}];validatePayload({version:10,operations:ops});const next=applyOperations(d,d.projects[0],ops),row=next.seedings[0];assert.equal(row.shipping,'미출고');assert.equal(row.trackingNumber,'');assert.equal(row.deliveredAt,'');assert.equal(row.deadline,'2026-10-17');assert.throws(()=>applyOperations(d,d.projects[0],[{...ops[0],patch:{...ops[0].patch,trackingNumber:'123'}}]));assert.throws(()=>validatePayload({version:10,operations:[{...ops[0],patch:{fulfillmentMethod:'pickup',pickedUpAt:'bad'}}]}));assert.deepEqual(d,initial());});
test('MCP create wraps exact POST and GET readback, never retries or creates recipients',async()=>{const calls=[],project={...validateCreate(input),id:'new',version:1},body={ok:true,project,seedings:[],creators:[],summary:{total:0}};const request=async(method,path,name,payload)=>{calls.push({method,path,name,payload});return {status:method==='POST'?201:200,body}};const result=await callSeedingTool('createSeedingProject',input,request);assert.equal(result.status,201);assert.equal(result.body.verified,true);assert.deepEqual(calls.map(c=>c.method),['POST','GET']);assert.deepEqual(calls[0].payload,input);const rpc=await seedingRpc({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'createSeedingProject',arguments:input}},request);assert.equal(rpc.body.result.isError,false);for(const status of [409,502]){let n=0;const fail=await callSeedingTool('createSeedingProject',input,async()=>{n++;return {status,body:{ok:false,error:'uncertain'}}});assert.equal(fail.status,status);assert.equal(n,1);}});
test('MCP POST fixed URL and server-side authentication, unchanged payload',async()=>{const request=createSeedingRestClient({baseUrl:'https://example.test',token:'isolated-token',fetchImpl:async(url,init)=>{assert.equal(url.href,'https://example.test/api/ai-audit/seeding/projects');assert.equal(init.method,'POST');assert.equal(init.headers['x-samplas-internal-token'],'isolated-token');assert.deepEqual(JSON.parse(init.body),input);return new Response(JSON.stringify({ok:true}),{status:201});}});assert.equal((await request('POST','projects',undefined,input)).status,201);assert.equal((await request('POST','project',undefined,input)).status,400);});
