import test from 'node:test';
import assert from 'node:assert/strict';
import {applyOperations,validatePayload,detail,handleSeeding,normalizeId,STORE_PATH} from '../scripts/seeding-store.mjs';
const fixture=()=>({schemaVersion:1,projects:[{id:'p',name:'MEANTIME',version:12,product:'pants'}],creators:[{id:'c',instagram:'purynn__',memo:''},{id:'reuse',instagram:'zyisue',memo:''}],seedings:[{id:'r',projectId:'p',creatorId:'c',shipping:'출고 완료',shippedAt:'2026-10-01',trackingNumber:'original',carrier:'CJ대한통운',deliveredAt:'',deadline:'2026-10-08',uploadStatus:'waiting',uploadStatusMode:'auto',postUrl:'',memo:'keep'}]});
test('normalization, allowlists and strict versions',()=>{assert.equal(normalizeId(' @Zyisue '),'zyisue');for(const body of [{version:12,operations:[{type:'bad'}]},{version:12,operations:[{type:'update_seeding',instagramId:'purynn__',patch:{creatorId:'hack'}}]},{version:'12',operations:[]}])assert.throws(()=>validatePayload(body));});
test('operations atomic, shipment preserved, delivery +7, duplicates forbidden',()=>{const doc=fixture();const ops=[{type:'update_seeding',instagramId:' @Purynn__ ',patch:{deliveredAt:'2026-10-07'}}];validatePayload({version:12,operations:ops});const next=applyOperations(doc,doc.projects[0],ops);assert.equal(next.seedings[0].deadline,'2026-10-14');assert.equal(next.seedings[0].shippedAt,'2026-10-01');assert.equal(doc.seedings[0].deliveredAt,'');assert.equal(next.projects[0].version,13);assert.throws(()=>applyOperations(doc,doc.projects[0],[{type:'add_seeding',instagramId:'PURYNN__'}]));const reused=applyOperations(doc,doc.projects[0],[{type:'add_creator_to_project',instagramId:'@Zyisue'}]);assert.equal(reused.creators.length,2);assert.equal(reused.seedings.length,2);assert.throws(()=>applyOperations(doc,doc.projects[0],[{type:'update_seeding',instagramId:'purynn__',patch:{memo:'change'}},{type:'remove_seeding',instagramId:'missing'}]));assert.equal(doc.seedings[0].memo,'keep');});
test('postURL completion and creator counts',()=>{const doc=fixture();const next=applyOperations(doc,doc.projects[0],[{type:'update_seeding',instagramId:'purynn__',patch:{postUrl:'https://www.instagram.com/p/confirmed/'}}]);const result=detail(next,next.projects[0]);assert.equal(result.seedings[0].uploadStatus,'completed');assert.equal(result.creators[0].uploadCompletedCount,1);assert.equal(result.seedings[0].trackingNumber,'original');});
function remote(options={}){let doc=fixture(),uploads=0;const fetchImpl=async(url,init)=>{if(url.includes('oauth2/token'))return new Response(JSON.stringify({access_token:'test'}));if(url.endsWith('/download'))return new Response(JSON.stringify(doc),{headers:{'dropbox-api-result':JSON.stringify({rev:'rev1'})}});if(url.endsWith('/upload')){uploads++;assert.equal(JSON.parse(init.headers['Dropbox-API-Arg']).path,STORE_PATH);assert.equal(JSON.parse(init.headers['Dropbox-API-Arg']).mode.update,'rev1');if(options.race){doc.projects[0].version=13;return new Response('{}',{status:409})}doc=JSON.parse(init.body);return new Response('{}');}throw Error(url)};return {fetchImpl,env:{DROPBOX_APP_KEY:'a',DROPBOX_APP_SECRET:'b',DROPBOX_REFRESH_TOKEN:'c'},uploads:()=>uploads};}
test('GET never writes, stale 409, unknown 404, CAS race 409 and successful readback',async()=>{const options=remote(),path='/api/ai-audit/seeding/project';assert.equal((await handleSeeding('GET',path,'MEANTIME',null,options)).body.project.version,12);assert.equal(options.uploads(),0);assert.equal((await handleSeeding('PUT',path,'MEANTIME',{version:11,operations:[{type:'update_seeding',instagramId:'purynn__',patch:{memo:'x'}}]},options)).status,409);await assert.rejects(()=>handleSeeding('GET',path,'missing',null,options),e=>e.status===404);await assert.rejects(()=>handleSeeding('PUT',path,'MEANTIME',{version:12,operations:[{type:'malformed'}]},options),e=>e.status===400);const result=await handleSeeding('PUT',path,'MEANTIME',{version:12,operations:[{type:'update_seeding',instagramId:'purynn__',patch:{memo:'confirmed'}}]},options);assert.equal(result.status,200);assert.equal((await handleSeeding('GET',path,'MEANTIME',null,options)).body.seedings[0].memo,'confirmed');const raced=await handleSeeding('PUT',path,'MEANTIME',{version:12,operations:[{type:'update_seeding',instagramId:'purynn__',patch:{memo:'x'}}]},remote({race:true}));assert.equal(raced.status,409);assert.equal(raced.body.currentVersion,13);});

test('form-only update never alters shipping or upload fields, reusable orphan creators remain visible',()=>{const doc=fixture(),r=doc.seedings[0];r.deliveredAt='2026-10-05';r.deliveryStatus='unknown';r.deadline='2026-10-20';r.uploadDeadline='2026-10-20';const next=applyOperations(doc,doc.projects[0],[{type:'update_seeding',instagramId:'purynn__',patch:{formStatus:'응답 완료',size:'M'}}]);for(const key of ['trackingNumber','carrier','shipping','shippedAt','deliveryStatus','deliveredAt','deadline','uploadDeadline','uploadStatus','postUrl','memo'])assert.equal(next.seedings[0][key],r[key]);assert.equal(detail(next,next.projects[0]).creators.length,2);assert.throws(()=>validatePayload({version:12,operations:[{type:'update_project',patch:{name:''}}]}));});
