import test from 'node:test';
import assert from 'node:assert/strict';
import {instagramHandles,searchProvider,discoverAccount,assessAccount,collectCandidates,runCandidateResearch,candidateScheduleDue,kstDate,evaluateCandidate} from '../scripts/seeding-candidates.mjs';
import {validatePayload,applyOperations,handleSeeding,mutateSeedingCandidates} from '../scripts/seeding-store.mjs';
const candidate={id:'candidate-0123456789abcdef0123',instagramId:'real_creator',verifiedAt:'2026-10-10T01:00:00Z',status:'pending'};
const document=()=>({schemaVersion:1,projects:[{id:'p',name:'TEST',version:1,product:'denim',aiCandidates:{items:[structuredClone(candidate)],runs:{},enabled:true}},{id:'other',name:'OTHER',version:5}],creators:[],seedings:[],unrelated:{keep:true}});
const review=status=>({type:'review_candidate',candidateId:candidate.id,status});
const now=new Date('2026-10-10T01:00:00Z');
const graph=handle=>({business_discovery:{username:handle,profile_picture_url:'https://cdn.example/profile.jpg',biography:'fashion denim',followers_count:1000,media:{data:[1,2,3].map(i=>({id:String(i),caption:'denim outfit',timestamp:now.toISOString(),media_type:'IMAGE',media_url:'https://cdn.example/'+i+'.jpg',permalink:'https://www.instagram.com/p/'+i+'/'}))}}});
const options={env:{TAVILY_API_KEY:'isolated'},token:'isolated',igId:'123',now,fetchImpl:async(url,init)=>{
 if(url.includes('tavily')){assert.equal(init.headers.Authorization,'Bearer isolated');return Response.json({results:[{url:'https://www.instagram.com/real_creator/'}]});}
 if(url.includes('graph.facebook')){assert.equal(init.headers.Authorization,'Bearer isolated');assert.ok(!url.includes('access_token'));return Response.json(graph('real_creator'));}throw Error('unexpected URL');}};
function remote(){let doc=document(),rev=1,uploads=0;return {get:()=>structuredClone(doc),uploads:()=>uploads,env:{DROPBOX_APP_KEY:'isolated',DROPBOX_APP_SECRET:'isolated',DROPBOX_REFRESH_TOKEN:'isolated'},fetchImpl:async(url,init)=>{if(url.includes('oauth2/token'))return Response.json({access_token:'isolated'});if(url.endsWith('/download'))return Response.json(doc,{headers:{'dropbox-api-result':JSON.stringify({rev:String(rev)})}});if(url.endsWith('/upload')){const arg=JSON.parse(init.headers['Dropbox-API-Arg']);assert.equal(arg.autorename,false);if(arg.mode.update!==String(rev))return Response.json({}, {status:409});doc=JSON.parse(init.body);rev++;uploads++;return Response.json({});}throw Error('unexpected URL');}};}
test('search extracts only real profile URL handles, normalizes and deduplicates',()=>{assert.deepEqual(instagramHandles([{url:'https://www.instagram.com/Real.Creator/'},{url:'https://instagram.com/real.creator/'},{url:'https://evil.test/another/'},{url:'https://instagram.com/p/abc/'},{url:'broken'}]).map(x=>x.instagramId),['real.creator']);});
test('provider priority, alternative and disconnected failure',()=>{assert.equal(searchProvider({TAVILY_API_KEY:'x',BRAVE_SEARCH_API_KEY:'y'}),'tavily');assert.equal(searchProvider({BRAVE_SEARCH_API_KEY:'y'}),'brave');assert.throws(()=>searchProvider({}),e=>e.status===503);});
test('discovery validates handle and returns real profile/media',async()=>{const p=await discoverAccount('real_creator',options);assert.equal(p.posts.length,3);assert.ok(p.profileImage);await assert.rejects(()=>discoverAccount('other',options));await assert.rejects(()=>discoverAccount('../',options),e=>e.status===400);});
test('evaluation explicitly separates evidence, missing dates and estimates',()=>{const a=assessAccount({biography:'denim',posts:[],followers:null},{product:'SCAR PATINE'},now);assert.match(a.salesEstimate,/추정/);assert.match(a.collaborationEstimate,/추정/);assert.equal(a.recentActivity,'게시일 데이터 부족');assert.equal(a.method,'caption-evidence');});
test('AI unavailable is explicit and optional visual evaluation validates response',async()=>{const account=await discoverAccount('real_creator',options);assert.equal((await evaluateCandidate(account,{},options)).aiStatus,'NOT_CONFIGURED');const a=await evaluateCandidate(account,{}, {...options,env:{OPENAI_API_KEY:'isolated'},fetchImpl:async()=>Response.json({choices:[{message:{content:JSON.stringify({styleFit:'test',denimFit:'test',salesEstimate:'unknown',collaborationEstimate:'unknown',reason:'evidence'})}}]})});assert.equal(a.aiStatus,'evaluated');assert.match(a.salesEstimate,/미검증/);});
test('collect only verified accounts, 3 actual images; no creators/history duplicates',async()=>{const result=await collectCandidates({project:{},creators:[]},options);assert.equal(result.items.length,1);assert.equal(result.items[0].posts.length,3);const duplicate=await collectCandidates({project:{},creators:[{instagramId:'REAL_CREATOR'}]},options);assert.equal(duplicate.items.length,0);});
test('excluded and held candidates cannot be recommended again',async()=>{for(const status of ['held','excluded']){const result=await collectCandidates({project:{aiCandidates:{items:[{...candidate,status}]}},creators:[]},options);assert.equal(result.items.length,0);}});
test('API failure never fabricates successful batch',async()=>{await assert.rejects(()=>collectCandidates({project:{},creators:[]},{...options,fetchImpl:async()=>{throw Error('sensitive URL/token');}}),e=>e.message==='EXTERNAL_REQUEST_FAILED');});
test('shop owner and large accounts get exclusion evidence',()=>{assert.ok(assessAccount({biography:'쇼핑몰 대표',posts:[],followers:100},{}).exclusions.length);assert.ok(assessAccount({biography:'',posts:[],followers:400000},{}).exclusions.length);});
test('review allowlist rejects forged verified candidates',()=>{validatePayload({version:1,operations:[review('approved')]});assert.throws(()=>validatePayload({version:1,operations:[{...review('approved'),candidate:{verified:true}}]}));assert.throws(()=>validatePayload({version:1,operations:[review('fake')]}));});
test('approval and canonical seeding registration are atomic, preserve other project',()=>{const doc=document(),next=applyOperations(doc,doc.projects[0],[review('approved')]);assert.equal(next.creators.length,1);assert.equal(next.seedings.length,1);assert.equal(next.projects[0].aiCandidates.items[0].status,'approved');assert.equal(next.projects[0].version,2);assert.deepEqual(next.projects[1],doc.projects[1]);assert.deepEqual(next.unrelated,doc.unrelated);assert.equal(doc.seedings.length,0);assert.throws(()=>applyOperations(next,next.projects[0],[review('approved')]),e=>e.status===409);});
test('hold preserves candidate; exclusion is permanent; no seeding added',()=>{let d=document();d=applyOperations(d,d.projects[0],[review('held')]);assert.equal(d.seedings.length,0);d=applyOperations(d,d.projects[0],[review('excluded')]);assert.throws(()=>applyOperations(d,d.projects[0],[review('approved')]),e=>e.status===409);});
test('existing Creator DB duplicate registration refused',()=>{const d=document();d.creators.push({id:'c',instagram:'REAL_CREATOR'});assert.throws(()=>applyOperations(d,d.projects[0],[review('approved')]),e=>e.status===409);assert.equal(d.seedings.length,0);});
test('version conflict and readback use unchanged Dropbox rev contract',async()=>{const r=remote();const saved=await handleSeeding('PUT','/project','TEST',{version:1,operations:[review('approved')]},r);assert.equal(saved.status,200);assert.equal(r.uploads(),1);const latest=await handleSeeding('GET','/project','TEST',undefined,r);assert.equal(latest.body.project.aiCandidates.items[0].status,'approved');assert.equal(latest.body.seedings.length,1);assert.equal((await handleSeeding('PUT','/project','TEST',{version:1,operations:[review('held')]},r)).status,409);assert.equal(r.uploads(),1);});
test('internal research mutation uses CAS and preserves records',async()=>{const r=remote(),before=r.get();await mutateSeedingCandidates('TEST',1,p=>p.aiCandidates.runs.x={status:'running'},r);assert.deepEqual(r.get().seedings,before.seedings);await assert.rejects(()=>mutateSeedingCandidates('TEST',1,()=>{},r),e=>e.status===409);});
test('KST 10am schedule requires project opt-in and prevents date duplicates',()=>{const p=document().projects[0];assert.equal(kstDate(now),'2026-10-10');assert.equal(candidateScheduleDue(p,new Date('2026-10-10T00:59:00Z')),false);assert.equal(candidateScheduleDue(p,now),true);p.aiCandidates.runs['2026-10-10']={status:'complete'};assert.equal(candidateScheduleDue(p,now),false);assert.equal(candidateScheduleDue({},now),false);});
function memoryRun(){let detail={project:{id:'p',name:'TEST',version:1,aiCandidates:{items:[],runs:{}}},creators:[]};return {get:()=>structuredClone(detail),load:async()=>structuredClone(detail),mutate:async(name,version,fn)=>{assert.equal(version,detail.project.version);fn(detail.project);detail.project.version++;return structuredClone(detail);}};}
test('daily run claims before fetch, stores verified only and does not duplicate',async()=>{const store=memoryRun();await runCandidateResearch('TEST',{...options,...store});assert.equal(store.get().project.aiCandidates.items.length,1);assert.equal(store.get().project.aiCandidates.runs['2026-10-10'].count,1);await assert.rejects(()=>runCandidateResearch('TEST',{...options,...store}),e=>e.status===409);});
test('run failure preserves existing candidates and records failure not success',async()=>{const store=memoryRun();await assert.rejects(()=>runCandidateResearch('TEST',{...options,...store,fetchImpl:async()=>{throw Error('network');}}));assert.equal(store.get().project.aiCandidates.runs['2026-10-10'].status,'error');assert.equal(store.get().project.aiCandidates.items.length,0);});
test('missing search credential does not mutate even run metadata',async()=>{const store=memoryRun();await assert.rejects(()=>runCandidateResearch('TEST',{...options,...store,env:{}}));assert.equal(store.get().project.version,1);});
test('concurrent claim conflict never retries',async()=>{let calls=0;await assert.rejects(()=>runCandidateResearch('TEST',{...options,load:async()=>({project:{version:1},creators:[]}),mutate:async()=>{calls++;throw Object.assign(Error('version_conflict'),{status:409});}}));assert.equal(calls,1);});
test('whole-document Dropbox rev collision fails closed without retries',async()=>{const r=remote();let attempts=0;const base=r.fetchImpl;r.fetchImpl=async(url,init)=>{if(url.endsWith('/upload')){attempts++;return Response.json({},{status:409});}return base(url,init);};await assert.rejects(()=>mutateSeedingCandidates('TEST',1,p=>p.aiCandidates.runs.x={status:'running'},r),e=>e.status===409);assert.equal(attempts,1);assert.deepEqual(r.get(),document());});
test('latest Creator change during research blocks final candidate insertion',async()=>{const store=memoryRun();let reads=0;const load=async()=>{const d=store.get();if(++reads>1)d.creators=[{instagramId:'real_creator'}];return d;};await runCandidateResearch('TEST',{...options,...store,load});assert.equal(store.get().project.aiCandidates.items.length,0);});
test('expired media URL refresh is read-only and returns current discovery URL',async()=>{const d=document(),before=structuredClone(d);const profile=await discoverAccount('real_creator',{...options,fetchImpl:async()=>Response.json(graph('real_creator'))});assert.ok(profile.posts.every(p=>p.imageUrl.startsWith('https://cdn.example/')));assert.deepEqual(d,before);});
test('partial batch exposes coverage, successful zero search result is truly zero',async()=>{const batch=await collectCandidates({project:{},creators:[]},{...options,fetchImpl:async()=>Response.json({results:[]})});assert.deepEqual(batch.items,[]);assert.equal(batch.discovered,0);});
test('multiple operations roll back approval if any operation fails',()=>{const doc=document();assert.throws(()=>applyOperations(doc,doc.projects[0],[review('approved'),{type:'update_seeding',instagramId:'missing',patch:{memo:'x'}}]));assert.deepEqual(doc,document());});

const registration=async()=>import('../scripts/seeding-candidates.mjs');
const registrationBody=(count=5)=>({name:'TEST',version:1,candidates:Array.from({length:count},(_,i)=>({instagramId:'isolated_'+i,profileUrl:'https://www.instagram.com/isolated_'+i+'/',recommendationReason:'Isolated submitted research only',source:'Isolated public search fixture'}))});
const registrar=r=>({load:async name=>(await handleSeeding('GET','/project',name,undefined,r)).body,mutate:(name,version,fn)=>mutateSeedingCandidates(name,version,fn,r)});
test('ChatGPT batch registers 5 and 10 without any search or model credentials; image failure is nonfatal',async()=>{
 const {registerCandidates}=await registration();for(const count of [5,10]){const r=remote(),before=r.get(),result=await registerCandidates(registrationBody(count),registrar(r));assert.equal(result.project.aiCandidates.items.length,count+1);assert.equal(result.project.version,2);assert.equal(r.uploads(),1);assert.equal(result.seedings.length,0);for(const c of result.project.aiCandidates.items.slice(1)){assert.equal(c.imageStatus,'unavailable');assert.equal(c.imageError,'IMAGE_UNAVAILABLE');assert.equal(c.verifiedAt,undefined);assert.equal(c.status,'pending');assert.equal(c.assessment.reasons[0],'Isolated submitted research only');}assert.deepEqual(r.get().creators,before.creators);assert.deepEqual(r.get().projects[1],before.projects[1]);}
});
test('registration preserves confirmed Meta images and provenance, without rewriting supplied reason',async()=>{const {registerCandidates}=await registration(),r=remote(),body=registrationBody(1);const result=await registerCandidates(body,{...options,...registrar(r),fetchImpl:async()=>Response.json(graph('isolated_0'))});const item=result.project.aiCandidates.items[1];assert.equal(item.imageStatus,'available');assert.equal(item.posts.length,3);assert.ok(item.verifiedAt);assert.equal(item.origin,'chatgpt-research');assert.equal(item.source,body.candidates[0].source);});
test('partial Meta failure registers all requested candidates, unavailable ones remain reviewable',async()=>{const {registerCandidates}=await registration(),r=remote();const result=await registerCandidates(registrationBody(5),{...options,...registrar(r),fetchImpl:async url=>{const fields=new URL(url).searchParams.get('fields'),handle=fields.match(/username\(([^)]+)\)/)[1];return handle==='isolated_2'?Response.json({error:{}},{status:400}):Response.json(graph(handle));}});const items=result.project.aiCandidates.items.slice(1);assert.equal(items.filter(c=>c.imageStatus==='available').length,4);assert.equal(items.filter(c=>c.imageStatus==='unavailable').length,1);assert.equal(r.uploads(),1);});
test('duplicate normalized handles inside batch and invalid payload fail before I/O',async()=>{const {registerCandidates}=await registration();for(const mutate of [b=>b.candidates.push({...b.candidates[0],instagramId:'@ISOLATED_0'}),b=>b.candidates[0].profileUrl='https://evil.test/isolated_0/',b=>b.candidates[0].profileUrl='https://instagram.com/wrong/',b=>b.candidates[0].status='approved',b=>b.candidates[0].recommendationReason='',b=>b.candidates[0].source='',b=>b.candidates[0].instagramId='../x',b=>b.version=0,b=>b.candidates=Array(11).fill(b.candidates[0])]){const body=registrationBody(1);mutate(body);let calls=0;await assert.rejects(()=>registerCandidates(body,{load:async()=>{calls++;}}));assert.equal(calls,0);}});
test('existing candidate, approved and excluded history block re-registration; retry never duplicates',async()=>{const {registerCandidates}=await registration();for(const status of ['pending','held','approved','excluded']){const r=remote();await mutateSeedingCandidates('TEST',1,p=>p.aiCandidates.items[0].status=status,r);const body=registrationBody(1);body.version=2;body.candidates[0]={...body.candidates[0],instagramId:'@REAL_CREATOR',profileUrl:'https://instagram.com/real_creator/'};await assert.rejects(()=>registerCandidates(body,registrar(r)),e=>e.status===409&&e.message===(status==='excluded'?'candidate_excluded':status==='approved'?'candidate_already_approved':'duplicate_candidate'));assert.equal(r.uploads(),1);}
 const r=remote();await registerCandidates(registrationBody(5),registrar(r));await assert.rejects(()=>registerCandidates(registrationBody(5),registrar(r)),e=>e.message==='version_conflict');const retry=registrationBody(5);retry.version=2;await assert.rejects(()=>registerCandidates(retry,registrar(r)),e=>e.message==='duplicate_candidate');assert.equal(r.uploads(),1);
});
test('Creator DB across projects blocks new candidate, including concurrent Creator additions',async()=>{const {registerCandidates,assertRegistrationAllowed}=await registration();assert.throws(()=>assertRegistrationAllowed({project:{},creators:[{instagram:'ISOLATED_0'}]},registrationBody(1).candidates),e=>e.message==='creator_already_exists');const r=remote(),ops=registrar(r);await assert.rejects(()=>registerCandidates(registrationBody(1),{...ops,mutate:(name,version,fn)=>mutateSeedingCandidates(name,version,(p,doc)=>{doc.creators.push({id:'other-c',instagram:'isolated_0'});fn(p,doc);},r)}),e=>e.message==='creator_already_exists');assert.equal(r.uploads(),0);});
test('image-unavailable candidate can be held/excluded or explicitly approved; only approval creates seeding',async()=>{const {registerCandidates}=await registration(),r=remote();const saved=await registerCandidates(registrationBody(5),registrar(r)),id=saved.project.aiCandidates.items[1].id;let v=2;for(const status of ['held','approved']){const result=await handleSeeding('PUT','/project','TEST',{version:v++,operations:[{type:'review_candidate',candidateId:id,status}]},r);assert.equal(result.status,200);assert.equal(result.body.seedings.length,status==='approved'?1:0);}assert.equal(r.get().seedings.length,1);});
test('registration unknown project, stale version and Dropbox CAS collision do not retry',async()=>{const {registerCandidates}=await registration(),r=remote();const unknown=registrationBody(1);unknown.name='UNKNOWN';await assert.rejects(()=>registerCandidates(unknown,registrar(r)),e=>e.status===404);const stale=registrationBody(1);stale.version=2;await assert.rejects(()=>registerCandidates(stale,registrar(r)),e=>e.status===409);let attempts=0;const base=r.fetchImpl;r.fetchImpl=async(url,init)=>{if(url.endsWith('/upload')){attempts++;return Response.json({},{status:409});}return base(url,init);};await assert.rejects(()=>registerCandidates(registrationBody(1),registrar(r)),e=>e.status===409);assert.equal(attempts,1);assert.equal(r.get().projects[0].aiCandidates.items.length,1);});
test('unpublished Plugin contract matches exact POST schema and contains no token value',async()=>{const {readFile}=await import('node:fs/promises');const tool=JSON.parse(await readFile(new URL('../docs/seeding-candidates-tool.json',import.meta.url))),api=JSON.parse(await readFile(new URL('../docs/seeding-candidates-openapi.json',import.meta.url)));assert.equal(tool.name,'registerSeedingCandidates');const route=api.paths['/api/ai-audit/seeding/candidates'].post;assert.deepEqual(route.requestBody.content['application/json'].schema,tool.inputSchema);assert.deepEqual(tool.inputSchema.required,['name','version','candidates']);assert.equal(tool.inputSchema.properties.candidates.maxItems,10);assert.equal(api.components.securitySchemes.InternalToken.name,'x-samplas-internal-token');assert.match(tool.description,/No automatic retry/);});
