import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {validateVeilCaption,queueItems,previewVeilPosts,runVeilFoundPublisher,resolveVeilFoundSlot} from '../scripts/veil-found-publisher.mjs';
import {createVeilControl,VEIL_TOOLS,validateUploadInput} from '../scripts/veil-found-control.mjs';
import worker from '../veil-found-plugin/worker/index.mjs';
const env={VEIL_FOUND_IG_TOKEN:'isolated-ig',VEIL_FOUND_IG_USER_ID:'isolated',DROPBOX_APP_KEY:'a',DROPBOX_APP_SECRET:'b',DROPBOX_REFRESH_TOKEN:'c',VEIL_FOUND_READY_DIR:'/READY',VEIL_FOUND_UPLOADED_DIR:'/UPLOADED'};
const caption=n=>`VEIL FOUND #${String(n).padStart(3,'0')}\nBRAND\nPRODUCT\n348,000 KRW`;
const post=n=>({number:n,path:`/READY/#${n}.png`,revision:'r1',caption:caption(n)});
function mock({duplicate=false,failPublish=false,invalidCaption=false}={}){const calls=[];const images=Array.from({length:10},(_,i)=>({'.tag':'file',name:`#${i+25}.png`,path_lower:`/READY/#${i+25}.png`,rev:'r1'}));const fetchImpl=async(u,o={})=>{const url=String(u);calls.push({url,options:o});const json=(body,status=200)=>new Response(JSON.stringify(body),{status});if(url.includes('/oauth2/token'))return json({access_token:'isolated-db'});if(url.endsWith('/files/list_folder'))return json({entries:[...images,{'.tag':'folder',name:'VEIL_FOUND_025-034'}]});if(url.endsWith('/files/download')){const path=JSON.parse(o.headers['Dropbox-API-Arg']).path;const n=Number(path.match(/\/(\d+)\/caption/)[1]);return new Response(invalidCaption?'bad':caption(n));}if(url.includes('graph.instagram.com')&&url.includes('/media?'))return json({data:duplicate?[{caption:'#025',id:'published'}]:[]});if(url.endsWith('/files/get_temporary_link'))return json({link:'https://isolated-image.test/original.png'});if(url.endsWith('/files/move_v2'))return json({metadata:{}});if(url.endsWith('/media_publish'))return failPublish?json({error:{message:'rejected',code:36003}},400):json({id:'media-id'});if(url.endsWith('/media'))return json({id:'container-id'});if(url.includes('/container-id?'))return json({status_code:'FINISHED'});throw Error('Unexpected mock request');};return {calls,fetchImpl};}
async function fixture(fn){const dir=await mkdtemp(join(tmpdir(),'veil-isolated-'));try{return await fn(dir)}finally{await rm(dir,{recursive:true,force:true})}}
test('PNG and JPEG accepted, #25–#34 numbers exact',()=>{assert.deepEqual(queueItems(Array.from({length:10},(_,i)=>({'.tag':'file',name:`#${25+i}.png`}))).map(i=>i.number),[25,26,27,28,29,30,31,32,33,34]);assert.equal(queueItems([{'.tag':'file',name:'#35.jpeg'}]).length,1);});
for(let n=25;n<=34;n++)test(`caption exact four lines #${n}`,()=>assert.equal(validateVeilCaption(caption(n),n),caption(n)));
test('caption rejects wrong number, missing price, extra line; SOLD OUT preserved',()=>{for(const c of [caption(25),caption(26)+'\nextra','VEIL FOUND #026\nB\nP\n'])assert.throws(()=>validateVeilCaption(c,26));assert.equal(validateVeilCaption(caption(26).replace('348,000 KRW','SOLD OUT'),26).split('\n')[3],'SOLD OUT');});
test('preview ten exact image/caption matches; zero Graph writes or moves',async()=>{const m=mock();const p=await previewVeilPosts({env,fetchImpl:m.fetchImpl});assert.equal(p.posts.length,10);for(const p0 of p.posts){assert.equal(p0.valid,true);assert.equal(p0.caption,caption(p0.number));assert.match(p0.captionPath,new RegExp('/0'+p0.number+'/caption.txt$'));}assert.ok(m.calls.every(c=>!c.url.endsWith('move_v2')&&!(c.url.includes('graph.instagram.com')&&c.options.method==='POST')));});
test('preview real Instagram duplicate flag',async()=>{const m=mock({duplicate:true});assert.equal((await previewVeilPosts({env,fetchImpl:m.fetchImpl})).posts[0].duplicate,true);});
test('publish selected PNG original URL and full caption only; moves after media id',()=>fixture(async workDir=>{const m=mock();const out=await runVeilFoundPublisher({env,workDir,force:true,approvedPosts:[post(25)],fetchImpl:m.fetchImpl,sleepImpl:async()=>{}});assert.equal(out.publishedNow.length,1);const graph=m.calls.find(c=>c.url.endsWith('/media'));const params=new URLSearchParams(graph.options.body);assert.equal(params.get('caption'),caption(25));assert.equal(params.get('image_url'),'https://isolated-image.test/original.png');assert.ok(m.calls.findIndex(c=>c.url.endsWith('move_v2'))>m.calls.findIndex(c=>c.url.endsWith('media_publish')));assert.equal(m.calls.filter(c=>c.url.endsWith('move_v2')).length,1);await assert.rejects(readFile(join(workDir,'veil-found-publisher-state.json')),{code:'ENOENT'});}));
test('publish API failure never moves image',()=>fixture(async workDir=>{const m=mock({failPublish:true});await assert.rejects(runVeilFoundPublisher({env,workDir,force:true,approvedPosts:[post(25)],fetchImpl:m.fetchImpl}));assert.equal(m.calls.filter(c=>c.url.endsWith('move_v2')).length,0);}));
test('caption failure blocks before all Graph writes',()=>fixture(async workDir=>{const m=mock({invalidCaption:true});await assert.rejects(runVeilFoundPublisher({env,workDir,force:true,approvedPosts:[post(25)],fetchImpl:m.fetchImpl}));assert.equal(m.calls.filter(c=>c.url.includes('graph.instagram.com')&&c.options.method==='POST').length,0);}));
test('changed approval revision blocks write',()=>fixture(async workDir=>{const m=mock();await assert.rejects(runVeilFoundPublisher({env,workDir,force:true,approvedPosts:[{...post(25),revision:'old'}],fetchImpl:m.fetchImpl}),/approved_post_changed/);}));
test('Friday 20:00 KST unchanged',()=>{assert.equal(resolveVeilFoundSlot(new Date('2026-10-09T11:00:00Z')).key,'2026-10-09@20:00');assert.equal(resolveVeilFoundSlot(new Date('2026-10-09T10:59:00Z')),null);});
const input={approval:true,requestId:'isolated-request',posts:[post(25)]};
function control(workDir,options={}){return createVeilControl({workDir,env:{},now:()=>new Date('2026-10-10T00:00:00Z'),preview:async()=>({ok:true,posts:[{...post(25),valid:true,duplicate:false}]}),publish:async()=>({ok:true,skipped:false}),status:async()=>({configured:true}),...options});}
test('all five tools exact names',()=>assert.deepEqual(VEIL_TOOLS.map(t=>t.name),['getUploadStatus','previewReadyPosts','scheduleUpload','runUpload','getUploadHistory']));
test('approval, request id, timezone, future and duplicate validation',()=>{for(const args of [{...input,approval:false},{...input,requestId:'x'},{...input,posts:[post(25),post(25)]},{...input,unexpected:true}])assert.throws(()=>validateUploadInput('runUpload',args));for(const date of ['2026-10-09T00:00:00Z','2026-10-11T12:00:00','nonsense'])assert.throws(()=>validateUploadInput('scheduleUpload',{...input,scheduledAt:date},new Date('2026-10-10')));});
test('schedule durable, disabled tick never publishes',()=>fixture(async workDir=>{let calls=0;const c=control(workDir,{publish:async()=>{calls++;}});await c.call('scheduleUpload',{...input,scheduledAt:'2026-10-10T12:00:00+09:00'});assert.equal((await c.tick()).reason,'disabled');assert.equal(calls,0);assert.equal((await control(workDir).call('getUploadHistory')).requests[0].status,'scheduled');}));
test('run idempotency and request conflict; no blind retry after network error',()=>fixture(async workDir=>{let calls=0;const c=control(workDir,{publish:async()=>{calls++;throw Error('SECRET_NOT_TO_EXPOSE')}});assert.equal((await c.call('runUpload',input)).request.status,'failed_or_unknown');assert.equal((await c.call('runUpload',input)).replayed,true);assert.equal(calls,1);await assert.rejects(c.call('runUpload',{...input,posts:[post(26)]}),/request_id_conflict/);assert.ok(!JSON.stringify(await c.call('getUploadHistory')).includes('SECRET_NOT_TO_EXPOSE'));}));
test('duplicate or changed preview rejects before writes',()=>fixture(async workDir=>{for(const change of [{duplicate:true},{caption:'changed'},{valid:false}]){const c=control(workDir,{preview:async()=>({posts:[{...post(25),valid:true,...change}]})});await assert.rejects(c.call('runUpload',input),/preview_changed_or_duplicate/);}}));
test('enabled isolated schedule runs once, retains history and no retry',()=>fixture(async workDir=>{let now=new Date('2026-10-10'),calls=0;const c=control(workDir,{env:{VEIL_FOUND_ONCE_ENABLED:'true'},now:()=>now,publish:async()=>{calls++;return {ok:true,skipped:false}}});await c.call('scheduleUpload',{...input,scheduledAt:'2026-10-10T01:00:00Z'});now=new Date('2026-10-10T02:00:00Z');await c.tick();await c.tick();assert.equal(calls,1);assert.equal((await c.call('getUploadHistory')).requests[0].status,'succeeded');}));
test('Site exposes five tools, trusted identity/server secret required, no token leak',async()=>{const req=message=>new Request('https://isolated.test/mcp',{method:'POST',body:JSON.stringify(message)});const list=await (await worker.fetch(req({jsonrpc:'2.0',id:1,method:'tools/list'}),{})).json();assert.deepEqual(list.result.tools,VEIL_TOOLS);assert.equal((await worker.fetch(req({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'runUpload',arguments:input}}),{})).status,401);});
test('Site bridge exact endpoint/body/token; no automatic retry or redirects',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async(u,o)=>{calls++;assert.equal(u,'https://samplas-marketing-os.onrender.com/api/ai-audit/veil-found/mcp');assert.equal(o.redirect,'manual');assert.equal(o.headers['x-samplas-internal-token'],'isolated-secret');throw Error('isolated-secret')};try{const request=new Request('https://isolated.test/mcp',{method:'POST',headers:{'oai-authenticated-user-id':'test'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'getUploadStatus',arguments:{}}})});const response=await worker.fetch(request,{SAMPLAS_INTERNAL_TOKEN:'isolated-secret'});assert.ok(!JSON.stringify(await response.json()).includes('isolated-secret'));assert.equal(calls,1);}finally{globalThis.fetch=original;}});
test('same-number image duplicates both rejected, incomplete feed blocks preview',async()=>{const base=mock();const fetchDuplicate=async(u,o)=>{const r=await base.fetchImpl(u,o);if(String(u).endsWith('/files/list_folder')){const b=await r.json();b.entries.push({'.tag':'file',name:'#25.jpeg',path_lower:'/READY/#25.jpeg',rev:'r2'});return new Response(JSON.stringify(b));}return r;};const p=await previewVeilPosts({env,fetchImpl:fetchDuplicate});assert.equal(p.posts.filter(p=>p.number===25&&p.valid===false).length,2);const fetchPages=async(u,o)=>String(u).includes('graph.instagram.com')?new Response(JSON.stringify({data:[],paging:{next:'https://graph.instagram.com/next'}})):base.fetchImpl(u,o);await assert.rejects(previewVeilPosts({env,fetchImpl:fetchPages}),/coverage incomplete/);});
test('concurrent requests excluded and published event survives move failure',()=>fixture(async workDir=>{let release;const gate=new Promise(r=>release=r);const c=control(workDir,{publish:async({onEvent})=>{await gate;await onEvent({status:'published',number:25,mediaId:'confirmed'});throw Error('move failed');}});const first=c.call('runUpload',input);await new Promise(r=>setTimeout(r,25));await assert.rejects(c.call('runUpload',{...input,requestId:'another-request'}),/upload_busy/);release();await first;const history=await c.call('getUploadHistory');assert.ok(history.history.some(e=>e.mediaId==='confirmed'));assert.equal(history.requests[0].status,'failed_or_unknown');}));
