import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, writeFile, mkdtemp, readdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import ExcelJS from 'exceljs';
import { buildWeeklyInstagramReportModel, buildWeeklyInstagramReportWorkbook } from '../scripts/instagram-weekly-report.mjs';
import { buildWeeklyReportModel, buildWeeklyReportWorkbook } from '../scripts/naver-ads-weekly-report.mjs';
import { instagramWinners, instagramActions, reachRate, naverCampaignSignal } from '../scripts/weekly-report-presentation.mjs';
import { instagramDecision, naverDecision, unitFormat } from '../scripts/weekly-onepage-report.mjs';
import { runWeeklyReportPreview, handleWeeklyReportPreview, validateWeeklyPreviewRequest } from '../scripts/weekly-report-manual.mjs';
const dates={since:'2026-09-29',until:'2026-10-05',previousSince:'2026-09-22',previousUntil:'2026-09-28'};
const posts=[{id:'1',title:'착장 A',type:'릴스',date:'2026-10-01',reach:300,views:600,saves:40,shares:20,likes:100,comments:10,totalInteractions:170},{id:'2',title:'신상품 B',type:'피드',date:'2026-10-02',reach:100,views:200,saves:10,shares:5,likes:30,comments:2,totalInteractions:47},{id:'3',title:'미측정',type:'피드',reach:0,saves:null,shares:0,totalInteractions:0}];
const ig=()=>buildWeeklyInstagramReportModel({...dates,current:{ok:true,posts,stories:[{id:'story',date:'2026-10-01',reach:999999,unavailableReason:'missing'}]},previous:{ok:true,posts:[{...posts[0],reach:250,views:400,saves:30,shares:30}]}});
const current={spend:100000,impressions:199514,clicks:1398,cpc:72,ctr:0.7007,conversions:19,conversionValue:200000,conversionRate:1.36,cpa:5263,roas:2};
const previous={spend:100000,impressions:162474,clicks:1298,cpc:77,ctr:0.79,conversions:72,conversionValue:600000,conversionRate:5.55,cpa:1389,roas:6};
const nav=()=>buildWeeklyReportModel({...dates,current:{ok:true,summary:current,campaigns:[{...current,campaignId:'c',campaignName:'브랜드',status:'ACTIVE'}]},previous:{ok:true,summary:previous,campaigns:[{...previous,campaignId:'c',campaignName:'브랜드'}]}});
const cellText=w=>JSON.stringify(w.worksheets.filter(s=>s.state==='visible').map(s=>s.getSheetValues()));
const allText=w=>JSON.stringify(w.worksheets.map(s=>s.getSheetValues()));
const visible=w=>w.worksheets.filter(s=>s.state==='visible').map(s=>s.name);

test('Instagram one REPORT only; no hidden or raw sheets after XLSX round-trip',async()=>{const w=await buildWeeklyInstagramReportWorkbook(ig()),l=new ExcelJS.Workbook();await l.xlsx.load(await w.xlsx.writeBuffer());assert.deepEqual(l.worksheets.map(s=>s.name),['REPORT']);assert.equal(l.worksheets[0].state,'visible');});
test('Naver one REPORT only after XLSX round-trip',async()=>{const w=await buildWeeklyReportWorkbook(nav()),l=new ExcelJS.Workbook();await l.xlsx.load(await w.xlsx.writeBuffer());assert.deepEqual(l.worksheets.map(s=>s.name),['REPORT']);});
test('Fixed portrait one-page layout and section order',async()=>{for(const w of [await buildWeeklyInstagramReportWorkbook(ig()),await buildWeeklyReportWorkbook(nav())]){const s=w.getWorksheet('REPORT');assert.equal(s.pageSetup.orientation,'portrait');assert.equal(s.pageSetup.fitToHeight,1);assert.equal(s.pageSetup.fitToWidth,1);for(const [row,label] of [[13,'성과 비교'],[26,'핵심 판단'],[32,'상세 성과'],[43,'다음 액션'],[49,'DATA NOTE']])assert.match(String(s.getCell(row,1).value),new RegExp(label));assert.equal(s.rowCount,57);}});
test('Instagram account weekly reach never uses post sums or monthly snapshot',async()=>{const m=ig();m.accountSnapshot={followers:12340,reach:999999,profileVisits:500};const w=await buildWeeklyInstagramReportWorkbook(m),s=w.getWorksheet('REPORT');assert.equal(s.getCell('A6').value,12340);assert.equal(s.getCell('A6').numFmt,'#,##0"명"');assert.match(s.getCell('A7').value,/월간/);assert.equal(s.getCell('G6').value,'N/A');assert.equal(s.getCell('C17').value,'N/A');assert.equal(s.getCell('C19').value,'N/A');assert(!cellText(w).includes('999999'));});
test('Instagram measured weekly unique reach is used directly; prior comparison remains unavailable',async()=>{const m=ig();m.weeklyUniqueReach=1234;const s=(await buildWeeklyInstagramReportWorkbook(m)).getWorksheet('REPORT');assert.equal(s.getCell('G6').value,1234);assert.equal(s.getCell('C17').value,1234);assert.equal(s.getCell('E17').value,'N/A');});
test('Instagram unavailable account metrics are N/A and engagement uses actual post totals',async()=>{const s=(await buildWeeklyInstagramReportWorkbook(ig())).getWorksheet('REPORT');for(const cell of ['D6','J6','A10','D10'])assert.equal(s.getCell(cell).value,'N/A');assert.equal(s.getCell('G10').value,217);assert.equal(s.getCell('C21').value,217);assert.equal(s.getCell('C22').value,800);});
test('Instagram content metrics exact; participation denominator guarded',async()=>{const m=ig(),before=JSON.stringify(m),s=(await buildWeeklyInstagramReportWorkbook(m)).getWorksheet('REPORT');const row=s.getRows(34,8).find(r=>r.getCell(3).value==='착장 A');assert(row);for(const [col,key] of [[5,'reach'],[6,'views'],[7,'likes'],[8,'comments'],[9,'saves'],[10,'shares']])assert.equal(row.getCell(col).value,posts[0][key]);assert.equal(row.getCell(11).value,170/300);assert.equal(row.getCell(11).numFmt,'#,##0.00%');assert.equal(JSON.stringify(m),before);});
test('Instagram zero reach yields N/A while measured zero counts remain zero',async()=>{const m=buildWeeklyInstagramReportModel({...dates,current:{ok:true,posts:[{id:'z',reach:0,views:0,likes:0,comments:0,saves:0,shares:0,totalInteractions:0}]},previous:{ok:true,posts:[]}});const s=(await buildWeeklyInstagramReportWorkbook(m)).getWorksheet('REPORT');assert.equal(s.getCell('E34').value,0);assert.equal(s.getCell('I34').value,0);assert.equal(s.getCell('K34').value,'N/A');for(const n of [0,-1,null,NaN])assert.equal(reachRate(1,n),null);});
test('Story fallback zeros and missing coverage never enter summary or performance scaling',async()=>{const m=ig(),s=(await buildWeeklyInstagramReportWorkbook(m)).getWorksheet('REPORT');const row=s.getRows(34,8).find(r=>r.getCell(2).value==='Story');assert.equal(row.getCell(5).value,'N/A');assert.equal(row.getCell(12).value,'관찰');assert.equal(s.getCell('G10').value,217);assert(!cellText(await buildWeeklyInstagramReportWorkbook(m)).includes('999999'));});
test('Reel high distribution with weak reactions is never expanded',()=>{const strong={type:'릴스',reach:100,views:200,saves:10,shares:10,totalInteractions:40};assert.notEqual(instagramDecision({...strong,reach:10000,views:100000,saves:0,shares:0,totalInteractions:1},[strong,{...strong,reach:10000,views:100000,saves:0,shares:0,totalInteractions:1}]),'확대');});
test('Feed repeat decision requires deeper save/share/engagement signals',()=>{const low={type:'피드',reach:100,views:10000,saves:1,shares:1,totalInteractions:2},high={...low,views:100,saves:10,shares:5,totalInteractions:20};assert.equal(instagramDecision(high,[low,high]),'확대');assert.equal(instagramDecision(low,[low,high]),'개선');assert.equal(instagramDecision(high,[high]),'관찰');});
test('Reel expansion requires both distribution and measured reactions',()=>{const low={type:'릴스',reach:100,views:200,saves:1,shares:1,totalInteractions:4},high={...low,reach:200,views:400,saves:10,shares:5,totalInteractions:40};assert.equal(instagramDecision(high,[low,high]),'확대');});
test('At most four judgments, eight detail rows and three actions; source disclosure for truncation',async()=>{const m=ig();m.content=[...m.content,...m.content,...m.content,...m.content];m.actions=[...m.actions,...m.actions,...m.actions];const w=await buildWeeklyInstagramReportWorkbook(m),s=w.getWorksheet('REPORT');assert.equal(s.getCell('A31').value,null);assert.equal(s.getCell('A42').value,null);assert.equal(s.getCell('A47').value,null);assert.match(cellText(w),/상세 8/);});
test('Naver values and percent-point conversion unchanged',async()=>{const m=nav(),before=JSON.stringify(m),s=(await buildWeeklyReportWorkbook(m)).getWorksheet('REPORT');for(const [cell,key] of [['B34','spend'],['C34','impressions'],['D34','clicks'],['F34','cpc'],['G34','conversions'],['I34','conversionValue'],['J34','cpa'],['K34','roas']])assert.equal(s.getCell(cell).value,current[key]);assert.equal(s.getCell('E34').value,current.ctr/100);assert.equal(s.getCell('H34').value,current.conversionRate/100);assert.equal(s.getCell('C21').value,current.conversionRate/100);assert.equal(JSON.stringify(m),before);});
test('Naver dashboard has six cards and current/previous/WoW in fixed positions',async()=>{const s=(await buildWeeklyReportWorkbook(nav())).getWorksheet('REPORT');assert.equal(s.getCell('A6').value,100000);assert.equal(s.getCell('E6').value,1398);assert.equal(s.getCell('I6').value,72);assert.equal(s.getCell('A10').value,19);assert.equal(s.getCell('E10').value,200000);assert.equal(s.getCell('I10').value,2);assert.equal(s.getCell('E20').value,72);assert.equal(s.getCell('G20').value,(19-72)/72);});
test('Naver healthy traffic / broken conversion diagnosis retains tracking-first action',async()=>{const w=await buildWeeklyReportWorkbook(nav());assert.match(cellText(w),/입찰 축소보다 전환 추적·랜딩·재고·검색 품질/);assert.match(w.getWorksheet('REPORT').getCell('C44').value,/전환 이벤트/);assert.deepEqual(w.worksheets.map(s=>s.name),['REPORT']);});
test('Naver high CTR without conversions and low-volume high ROAS never justify scaling',()=>{assert.equal(naverDecision({spend:100,ctr:99,conversions:0}, {analysis:[]}),'축소 검토');assert.equal(naverDecision({spend:100,ctr:99,conversions:1,roas:100,wowSpend:0,wowConversionValue:50},{analysis:[]}),'유지');assert.equal(naverDecision({spend:100,conversions:null},{analysis:[]}),'관찰');});
test('Units, comma formats, 0/N/A and no abbreviations',async()=>{for(const w of [await buildWeeklyInstagramReportWorkbook(ig()),await buildWeeklyReportWorkbook(nav())]){const s=w.getWorksheet('REPORT');s.eachRow(row=>row.eachCell(c=>{if(typeof c.value==='number')assert.match(c.numFmt,/(#,##0|%|x)/);}));assert(!/\d[MK]\b/.test(cellText(w)));assert(!cellText(w).includes('undefined'));assert(!cellText(w).includes('Infinity'));}assert.equal(unitFormat('원'),'#,##0"원"');assert.equal(unitFormat('%'),'#,##0.00%');});
test('Naver missing unsupported levels disclosed without fabricated brands/groups',async()=>{const w=await buildWeeklyReportWorkbook(nav());assert.match(cellText(w),/캠페인 단위/);assert.match(cellText(w),/신규 브랜드 등록 여부는 미제공/);assert(!cellText(w).includes('/ncc/keywords'));});
test('Missing source/prior cannot assert improvement; source models stay immutable',async()=>{const m=buildWeeklyInstagramReportModel({...dates,current:{ok:true,posts:[]},previous:null}),s=(await buildWeeklyInstagramReportWorkbook(m)).getWorksheet('REPORT');assert.match(s.getCell('D27').value,/전주 비교 데이터가 없습니다/);const n=await buildWeeklyReportWorkbook(buildWeeklyReportModel({...dates,current:{ok:false},previous:null}));assert.equal(n.getWorksheet('REPORT').getCell('A6').value,'N/A');assert.match(n.getWorksheet('REPORT').getCell('D27').value,/보류/);});

test('Instagram format comparison uses only actual prior posts',async()=>{const m=ig(),s=(await buildWeeklyInstagramReportWorkbook(m)).getWorksheet('REPORT');assert.match(s.getCell('D29').value,/현재 Feed 2건 \/ Reel 1건 · 직전 Feed 0건 \/ Reel 1건/);assert.equal(m.previousContent.length,1);});

const fakeEnv={DROPBOX_APP_KEY:'fixture',DROPBOX_APP_SECRET:'fixture',DROPBOX_REFRESH_TOKEN:'fixture'};
const fetchers=()=>({instagram:async()=>({ok:true,posts}),naver:async()=>({ok:true,summary:current,campaigns:[]}),meta:async()=>({rows:[],totals:{spend:0}}),actualOrders:async()=>({source:'cafe24_inflow_queries',orders:[],trackingQueries:['meta_meantime_look','meta_ssage','meta_adv_catalog','meta_adv_image','meta_adv_video'].map(code=>({code,ok:true,complete:true,count:0}))}),actualAnalytics:async()=>({available:false,reason:'fixture'})});
for(const platform of ['instagram','naver','meta'])test(`Manual ${platform}: same generators/fetchers, unique preview path, destination, no scheduler mutation`,async()=>{
 const f=fetchers(),calls=[];for(const k of Object.keys(f)){const original=f[k];f[k]=async(...args)=>{calls.push([k,...args]);return original(...args);};}
 const state={lastRunSinceKey:'unchanged',lastSuccessAt:'unchanged',running:false},snapshot=JSON.stringify(state),paths=[];
 const env={...fakeEnv};const options={env,fetchers:f,hasPersistentMetaConnection:async()=>true,upload:async(w,{targetPath,env:passed})=>{assert.equal(passed,env);assert(targetPath.includes('_PREVIEW_'));assert(targetPath.endsWith('.xlsx'));paths.push(targetPath);const loaded=new ExcelJS.Workbook();await loaded.xlsx.load(await w.xlsx.writeBuffer());return {filePath:targetPath};}};
 const r=await runWeeklyReportPreview({platform,referenceDate:'2026-10-06',mode:'preview'},options);await runWeeklyReportPreview({platform,referenceDate:'2026-10-06',mode:'preview'},options);
 assert.equal(r.ok,true);assert.equal(r.until,platform==='meta'?'2026-10-04':'2026-10-05');assert.equal(r.mode,'preview');assert.notEqual(paths[0],paths[1]);assert.equal(JSON.stringify(state),snapshot);
 const folder={instagram:'/SAMPLAS WORK/병구 작업/인스타그램 리포트/',naver:'/SAMPLAS WORK/병구 작업/네이버 광고 리포트/',meta:'/SAMPLAS WORK/병구 작업/메타 광고/리포트/'}[platform];assert(paths.every(p=>p.startsWith(folder)));
 assert.equal(calls.filter(c=>c[0]===platform).length,platform==='meta'?12:4);if(platform==='meta'){assert.equal(calls.filter(c=>c[0]==='actualOrders').length,2);assert.equal(calls.filter(c=>c[0]==='actualAnalytics').length,2);}
});
test('Manual: date/platform/mode validation before any upstream call',()=>{
 for(const body of [{platform:'popup',mode:'preview'},{platform:'naver',mode:'official'},{platform:'naver',mode:'preview',referenceDate:'2026-02-30'},{platform:'naver',mode:'preview',referenceDate:'../x'}])assert.throws(()=>validateWeeklyPreviewRequest(body));
});
test('Manual: Meta requires persistent connection even with environment fallback token',async()=>{
 let called=false;await assert.rejects(runWeeklyReportPreview({platform:'meta',mode:'preview'},{env:{META_ACCESS_TOKEN:'fixture'},fetchers:{meta:()=>{called=true;}},hasPersistentMetaConnection:async()=>false}),/persistent_meta_connection_required/);assert.equal(called,false);
});
test('Manual: partial Dropbox configuration fails closed; override directory preserved',async()=>{
 await assert.rejects(runWeeklyReportPreview({platform:'instagram',mode:'preview'},{env:{DROPBOX_APP_KEY:'fixture'},fetchers:fetchers()}),/dropbox_partially_configured/);
 const r=await runWeeklyReportPreview({platform:'naver',mode:'preview'},{env:{...fakeEnv,DROPBOX_WEEKLY_REPORT_DIR:'/existing/custom'},fetchers:fetchers(),upload:async(w,{targetPath})=>({filePath:targetPath})});assert(r.filePath.startsWith('/existing/custom/'));
});
test('Manual: local preview does not overwrite an official report',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'weekly-preview-'));try {
  const official=join(dir,'INSTAGRAM_WEEKLY_2026-09-29_2026-10-05.xlsx');await writeFile(official,'official fixture');
  const r=await runWeeklyReportPreview({platform:'instagram',referenceDate:'2026-10-06',mode:'preview'},{env:{INSTAGRAM_WEEKLY_REPORT_DIR:dir},fetchers:fetchers()});assert.match(r.filePath,/_PREVIEW_/);assert.equal((await readdir(dir)).length,2);assert.equal(await readFile(official,'utf8'),'official fixture');
 }finally{await rm(dir,{recursive:true,force:true});}
});
test('Manual route: server binds existing internal authorization and adapters; GET denied, unauthorized POST denied',async()=>{
 const src=await readFile(new URL('../server.mjs',import.meta.url),'utf8');const route=src.slice(src.indexOf('    if (url.pathname === "/api/reports/weekly/run")'),src.indexOf('    if (url.pathname === "/api/meta-ads/score-weights")'));
 const deps={handleWeeklyReportPreview,req:null,res:{},url:new URL('http://internal/api/reports/weekly/run'),isAuthorizedInternalRequest:r=>r.headers['x-samplas-internal-token']==='fixture',readJsonBody:async()=>({platform:'instagram',referenceDate:'2026-10-06',mode:'preview'}),json:(r,body,status=200)=>({body,status}),env:{},readMetaTokenRecord:async()=>({accessToken:'fixture'}),fetchNaverAdsPerformanceForWeeklyReport:()=>{},buildInstagramRangeDataForWeeklyReport:()=>{},buildMetaAdsSummaryForWeeklyReport:()=>{},fetchCafe24ActualOrdersForWeeklyReport:()=>{},fetchCafe24AnalyticsForWeeklyReport:()=>{},runWeeklyReportPreview:async(body,options)=>{assert.equal(options.fetchers.instagram,deps.buildInstagramRangeDataForWeeklyReport);assert.equal(options.fetchers.meta,deps.buildMetaAdsSummaryForWeeklyReport);assert.equal(options.fetchers.naver,deps.fetchNaverAdsPerformanceForWeeklyReport);assert.equal(await options.hasPersistentMetaConnection(),true);return {ok:true};}};
 // Exercise the route with the actual scheduler state initializers in its lexical scope.
 for(const name of ['naverWeeklyReportScheduler','metaWeeklyReportScheduler','instagramWeeklyReportScheduler']) {
  const start=src.indexOf(`const ${name} = {`),end=src.indexOf('\n};',start)+3;
  deps[name]=new Function(src.slice(start,end)+`\nreturn ${name};`)();
  deps[name].lastRunSinceKey='scheduled-week';deps[name].lastSuccessAt='scheduled-success';
 }
 const schedulerBefore=JSON.stringify([deps.naverWeeklyReportScheduler,deps.metaWeeklyReportScheduler,deps.instagramWeeklyReportScheduler]);
 const fn=new (Object.getPrototypeOf(async function(){}).constructor)(...Object.keys(deps),route);
 deps.req={method:'GET',headers:{}};assert.equal((await fn(...Object.values(deps))).status,405);
 deps.req={method:'POST',headers:{}};assert.equal((await fn(...Object.values(deps))).status,401);
 deps.req={method:'POST',headers:{'x-samplas-internal-token':'fixture'}};assert.equal((await fn(...Object.values(deps))).status,200);
 assert.equal(JSON.stringify([deps.naverWeeklyReportScheduler,deps.metaWeeklyReportScheduler,deps.instagramWeeklyReportScheduler]),schedulerBefore);
});
test('Manual route: upstream error sanitized and unavailable source is not success',async()=>{
 const deps={authorized:()=>true,readBody:async()=>({}),json:(r,body,status)=>({body,status}),run:async()=>{throw Object.assign(new Error('fixture-private-token'),{status:401});}};
 const r=await handleWeeklyReportPreview({method:'POST'},{},deps);assert.equal(r.status,502);assert.equal(r.body.error,'weekly_preview_failed');
 deps.run=async()=>({ok:false,error:'unavailable',filePath:null});assert.equal((await handleWeeklyReportPreview({method:'POST'},{},deps)).status,502);
});
