const tools=[{"name":"getUploadStatus","description":"Read Meta/Dropbox connection and last results.","inputSchema":{"type":"object","additionalProperties":false,"properties":{}},"annotations":{"readOnlyHint":true,"destructiveHint":false,"idempotentHint":true,"openWorldHint":true}},{"name":"previewReadyPosts","description":"Read READY originals, exact four-line captions and real Instagram duplicates. Present posts to user before approval.","inputSchema":{"type":"object","additionalProperties":false,"properties":{}},"annotations":{"readOnlyHint":true,"destructiveHint":false,"idempotentHint":true,"openWorldHint":true}},{"name":"scheduleUpload","description":"Schedule once ONLY after explicit user approval of these previewed posts and time. Never retry an ambiguous request.","inputSchema":{"type":"object","additionalProperties":false,"properties":{"approval":{"const":true,"description":"Explicit user approval of exact previewed posts is required."},"requestId":{"type":"string","minLength":8,"maxLength":100},"posts":{"type":"array","minItems":1,"maxItems":10,"items":{"type":"object","additionalProperties":false,"required":["number","path","revision","caption"],"properties":{"number":{"type":"integer","minimum":1},"path":{"type":"string"},"revision":{"type":"string"},"caption":{"type":"string"}}}},"scheduledAt":{"type":"string","description":"ISO timestamp including Z or UTC offset; future time."}},"required":["approval","requestId","posts","scheduledAt"]},"annotations":{"readOnlyHint":false,"destructiveHint":true,"idempotentHint":false,"openWorldHint":true}},{"name":"runUpload","description":"Publish ONLY these explicitly user-approved previewed posts. Never retry an ambiguous request; read history first.","inputSchema":{"type":"object","additionalProperties":false,"properties":{"approval":{"const":true,"description":"Explicit user approval of exact previewed posts is required."},"requestId":{"type":"string","minLength":8,"maxLength":100},"posts":{"type":"array","minItems":1,"maxItems":10,"items":{"type":"object","additionalProperties":false,"required":["number","path","revision","caption"],"properties":{"number":{"type":"integer","minimum":1},"path":{"type":"string"},"revision":{"type":"string"},"caption":{"type":"string"}}}}},"required":["approval","requestId","posts"]},"annotations":{"readOnlyHint":false,"destructiveHint":true,"idempotentHint":false,"openWorldHint":true}},{"name":"getUploadHistory","description":"Read publication and schedule outcomes.","inputSchema":{"type":"object","additionalProperties":false,"properties":{}},"annotations":{"readOnlyHint":true,"destructiveHint":false,"idempotentHint":true,"openWorldHint":true}}];
const ENDPOINT='https://samplas-marketing-os.onrender.com/api/ai-audit/veil-found/mcp';
const versions=['2025-11-25','2025-06-18','2025-03-26','2024-11-05'];
const json=(body,status=200)=>new Response(body===null?null:JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const error=(id,code,message,status=200)=>json({jsonrpc:'2.0',id:id??null,error:{code,message}},status);
export default {async fetch(request,env){
 const url=new URL(request.url);
 if(url.pathname==='/')return new Response('<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>SAMPLAS VEIL FOUND</title><body style="font:16px system-ui;background:#f6f5f2;color:#242220;margin:40px"><h1>SAMPLAS VEIL FOUND</h1><p>비공개 ChatGPT MCP 연결 · SEEDING 운영 조회 및 사용자 요청 수정</p><p>getUploadStatus · previewReadyPosts · scheduleUpload · runUpload · getUploadHistory</p><p>'+ (env.SAMPLAS_INTERNAL_TOKEN?'서버 인증 설정됨':'서버 Secret 등록 필요: SAMPLAS_INTERNAL_TOKEN')+'</p></body></html>',{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});
 if(url.pathname!=='/mcp')return json({error:'not_found'},404);
 if(request.method!=='POST')return json({error:'POST required'},405);
 if(Number(request.headers.get('Content-Length')||0)>2000000)return json({error:'request_too_large'},413);
 let rpc;try{const text=await request.text();if(new TextEncoder().encode(text).length>2000000)return json({error:'request_too_large'},413);rpc=JSON.parse(text)}catch{return error(null,-32700,'Parse error',400)}
 if(!rpc||Array.isArray(rpc)||rpc.jsonrpc!=='2.0'||typeof rpc.method!=='string')return error(rpc?.id,-32600,'Invalid Request',400);
 if(rpc.method==='notifications/initialized'&&!Object.hasOwn(rpc,'id'))return json(null,202);
 if(!(typeof rpc.id==='string'||typeof rpc.id==='number'&&Number.isFinite(rpc.id)))return error(null,-32600,'Invalid id',400);
 if(rpc.method==='initialize')return json({jsonrpc:'2.0',id:rpc.id,result:{protocolVersion:versions.includes(rpc.params?.protocolVersion)?rpc.params.protocolVersion:versions[0],capabilities:{tools:{listChanged:false}},serverInfo:{name:'samplas-veil-found',version:'1.0.0'},instructions:'Preview exact images and captions first. Obtain explicit user approval of posts and time before scheduleUpload or runUpload. Never retry ambiguous writes. Read history and Instagram before another attempt.'}});
 if(rpc.method==='server/discover')return json({jsonrpc:'2.0',id:rpc.id,result:{supportedVersions:['2026-07-28'],capabilities:{tools:{}}}});
 if(rpc.method==='tools/list')return json({jsonrpc:'2.0',id:rpc.id,result:{tools}});
 if(rpc.method==='ping')return json({jsonrpc:'2.0',id:rpc.id,result:{}});
 if(rpc.method!=='tools/call')return error(rpc.id,-32601,'Method not found');
 if(!tools.some(t=>t.name===rpc.params?.name))return error(rpc.id,-32602,'Unknown tool');
 // Sites OAuth boundary supplies trusted identity and enforces the owner-only audience.
 if(!request.headers.get('oai-authenticated-user-id'))return error(rpc.id,-32001,'Authentication required',401);
 if(!env.SAMPLAS_INTERNAL_TOKEN)return json({jsonrpc:'2.0',id:rpc.id,result:{content:[{type:'text',text:'Setup incomplete: production API secret is not configured.'}],isError:true}});
 try{
  const response=await fetch(ENDPOINT,{method:'POST',redirect:'manual',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream','x-samplas-internal-token':env.SAMPLAS_INTERNAL_TOKEN},body:JSON.stringify(rpc),signal:AbortSignal.timeout(90000)});
  if(!response.ok||response.status>=300)return error(rpc.id,-32000,'Production MCP request failed. Read current state before retrying an update. HTTP '+response.status);
  let result;try{result=await response.json()}catch{return error(rpc.id,-32000,'Production MCP returned an invalid response. Read current state before retrying an update.')}
  if(result?.jsonrpc!=='2.0'||result.id!==rpc.id)return error(rpc.id,-32000,'Production MCP returned an invalid response.');
  return json(result);
 }catch{return error(rpc.id,-32000,'Production MCP request failed. Read current state before retrying an update.')}
}};
